# .goreleaser.yml
project_name: go-aws-sso
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
# Disabled for now as goreleaser is complaining about the windows/arm64 combo and probably no one is using this with win
#     - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "go-aws-sso"
    dir: .
    main: ./cmd/go-aws-sso

release:
  draft: true

changelog:
  skip: false

  use: git
  sort: asc
