# .goreleaser.yml
project_name: go-aws-sso

version: 2

builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "go-aws-sso"
    dir: .
    main: ./cmd/go-aws-sso

release:
  draft: true

brews:
  - repository:
      owner: theurichde
      name: homebrew-go-aws-sso
    directory: Formula
    homepage: https://github.com/theurichde/go-aws-sso
    description: "Interactive CLI tool for AWS Single Sign-On (SSO)"
    license: MIT
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "go-aws-sso"

changelog:
  use: git
  sort: asc
