# .goreleaser.yml
project_name: go-aws-sso
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "go-aws-sso"
    dir: .
    main: ./cmd/go-aws-sso

release:
  draft: true

changelog:
  skip: false

  use: git
  sort: asc
